-   gun:
    asset: 
        path: .\assets\gun2.png
        size: [30,30]
        offset: [-0,-0]
    rarity: Common
    nodes: [
        [0,0]
        ]
    effect: 
        damage: 1


-   cannon:
    asset: 
        path: .\assets\gun3.png
        size: [30,60]
        offset: [-0,-0]
    rarity: Common
    nodes: [
        [0,0],
        [0,1]
        ]
    effect: 
        damage: 1