gun:
  rarity: Common
  health: 5
  nodes: [
    [0,0]
    ]
  asset: 
    path: .\assets\gun2.png
    size: [30,30]
    offset: [-0,-0]

cannon:
  rarity: Common
  health: 5
  nodes: [
    [0,0],
    [0,1]
    ]
  asset: 
    path: .\assets\gun3.png
    size: [30,60]
    offset: [-0,-0]
